import React, { useState } from "react";
import { StyleSheet, View, FlatList, SafeAreaView, Text } from "react-native";
import AppPieChart from "../components/analysis/AppPieChart";
import PARKING from "../config/type_colors";

function AppPie() {
  const data = [
    {
      color: "#06FDF4",
      id: 1,
      label: "29.57%",
      name: "Parking",
      y: "89.60",
    },
    {
      color: "#DE8F85",
      id: 2,
      label: "31.35%",
      name: "Toll",
      y: "95.00",
    },
    {
      color: "#203665",
      id: 3,
      label: "39.08%",
      name: "Medical",
      y: "118.40",
    },
  ];

  return (
    <SafeAreaView>
      <View style={styles.Container}>
        <AppPieChart
          data={data}
          colorScale={[PARKING.PARKING,PARKING.MEDICAL,PARKING.TOLL]}
          value={900.12}
          metric="RM"
          content="claimed for all claim types"
          title="Claim Amount Percentage"
          subTitle="Generated by 13 claim types for last month"
        />
      </View>
    </SafeAreaView>
  );
}

export default AppPie;

const styles = StyleSheet.create({
  Container: {
    alignItems: "center",
    justifyContent: "space-around",
  },
});
