import React from 'react';
import { ScrollView, StyleSheet, View } from 'react-native';

import AppBarChart from '../../../components/analysis/AppBarChart';
import AppPieChart from '../../../components/analysis/AppPieChart';

import { getColorScale, getDistinctClaimTypesCount, getSortedPieData, getTotalAmount } from '../../../functions/pie-chart';
import { getDistinctClaimTypesCountLimit, getSortedBarData } from '../../../functions/bar-chart';

import { sampleClaims } from '../../../config/data';

function MyClaim() {
    const pieData = getSortedPieData( sampleClaims );
    const colorScale = getColorScale( pieData );
    const value = getTotalAmount( sampleClaims );
    const unique_type = getDistinctClaimTypesCount( sampleClaims );

    const barData = getSortedBarData( sampleClaims );

    return (
        <ScrollView style={ styles.container }>
            <View style={ styles.pie }>
                <AppPieChart
                    data={ pieData }
                    colorScale={ colorScale }
                    value={ value }
                    metric="RM"
                    content={`claimed for ${ unique_type } claim types`}
                    title="Claim Amount Percentage"
                    subTitle={`Generated by ${ unique_type } claim types for last month`}
                />
            </View>
            <AppBarChart
                title="Total Claim Amount"
                subTitle={`Generated by ${ getDistinctClaimTypesCountLimit(sampleClaims) } claim categories for last 3 months`}
                data={ barData }
            />
        </ScrollView>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        paddingHorizontal: 20
    },
    pie: {
        marginVertical: 30
    }
})

export default MyClaim;