import React from 'react';
import { ScrollView, StyleSheet } from 'react-native';
import { View } from 'react-native';

import AppBarChart from '../../components/analysis/AppBarChart';
import AppPieChart from '../../components/analysis/AppPieChart';
import Screen from '../../components/Screen';

import { getColorScale,getDistinctClaimTypesCount, getSortedPieData, getTotalAmount } from '../../functions/pie-chart';
import { getSortedBarData } from '../../functions/bar-chart';

import { sampleBar, sampleClaims } from '../../config/data';

function Dashboard() {
    const pieData = getSortedPieData( sampleClaims );
    const colorScale = getColorScale( pieData );
    const value = getTotalAmount( sampleClaims );
    const unique_type = getDistinctClaimTypesCount( sampleClaims );

    const barData = getSortedBarData( sampleClaims );

    return (
        <Screen>
            <ScrollView style={ styles.container }>
                <View style={{ marginBottom: 30 }}>
                    <AppPieChart
                        data={ pieData }
                        colorScale={ colorScale }
                        value={ value }
                        metric="RM"
                        content={`claimed for ${ unique_type } claim types`}
                        title="Claim Amount Percentage"
                        subTitle={`Generated by ${ unique_type } claim types for last month`}
                    />
                </View>
                <AppBarChart
                    title="Total Claim Amount"
                    subTitle="Generated by 5 claim categories for last 3 months"
                    data={ barData }
                />
            </ScrollView>
        </Screen>
    );
}

const styles = StyleSheet.create({
    container: {
        paddingHorizontal: 20
    }
})

export default Dashboard;