const sampleClaims = [
    {
        claim_id: '1',
        claim_type: 'Lodging',
        amount: 29.50,
        project_code: 'ALLO AJ/LRU/2019-01',
        status: 'pending',
        image: require('../assets/receipt.jpeg'),
        name: 'Ven Jin',
        department: 'Research & Development',
        user_profile: require('../assets/henry_cavill.jpg'),
        invoice_date: 'Tue 01 03 2023 08:00:00 GMT+0800 (Malaysia Time)',
        submission_date: 'Tue 01 03 2023 08:00:00 GMT+0800 (Malaysia Time)'
    },
    {
        claim_id: '2',
        claim_type: 'Meal Subsidy',
        amount: 96.50,
        project_code: 'ECO-SHOP WAREHOUSE',
        status: 'rejected',
        image: require('../assets/receipt.jpeg'),
        name: 'Ivan',
        department: 'Project Management Office',
        user_profile: require('../assets/henry_cavill.jpg'),
        invoice_date: 'Mon 01 02 2023 08:00:00 GMT+0800 (Malaysia Time)',
        submission_date: 'Mon 01 02 2023 08:00:00 GMT+0800 (Malaysia Time)'
    },
    {
        claim_id: '3',
        claim_type: 'Mileage',
        amount: 19.20,
        project_code: 'IJN PO NO 2000043231',
        status: 'rejected',
        image: require('../assets/receipt.jpeg'),
        name: 'Elaine',
        department: 'HR & Admin',
        user_profile: require('../assets/henry_cavill.jpg'),
        invoice_date: 'Sun 01 01 2023 08:00:00 GMT+0800 (Malaysia Time)',
        submission_date: 'Sun 01 01 2023 08:00:00 GMT+0800 (Malaysia Time)'
    },
    {
        claim_id: '4',
        claim_type: 'Parking',
        amount: 83.50,
        project_code: 'KLCC-PHASE 4',
        status: 'rejected',
        image: require('../assets/receipt.jpeg'),
        name: 'Martin',
        department: 'Channel & Enterprise Sales',
        user_profile: require('../assets/henry_cavill.jpg'),
        invoice_date: 'Wed 01 04 2023 08:00:00 GMT+0800 (Malaysia Time)',
        submission_date: 'Wed 01 04 2023 08:00:00 GMT+0800 (Malaysia Time)'
    },
    {
        claim_id: '5',
        claim_type: 'Petrol',
        amount: 58.90,
        project_code: 'MAHB CCTV_KLIA',
        status: 'rejected',
        image: require('../assets/receipt.jpeg'),
        name: 'Ivan',
        department: 'Project Management Office',
        user_profile: require('../assets/henry_cavill.jpg'),
        invoice_date: 'Thu 01 05 2023 08:00:00 GMT+0800 (Malaysia Time)',
        submission_date: 'Thu 01 05 2023 08:00:00 GMT+0800 (Malaysia Time)'
    },
    {
        claim_id: '6',
        claim_type: 'Public Transport Fares',
        amount: 2.50,
        project_code: 'MINDEF MARINE SABAH',
        status: 'rejected',
        image: require('../assets/receipt.jpeg'),
        name: 'Ven Jin',
        department: 'Research & Development',
        user_profile: require('../assets/henry_cavill.jpg'),
        invoice_date: 'Fri 01 06 2023 08:00:00 GMT+0800 (Malaysia Time)',
        submission_date: 'Fri 01 06 2023 08:00:00 GMT+0800 (Malaysia Time)'
    },
    {
        claim_id: '7',
        claim_type: 'Travel Requisition',
        amount: 422.60,
        project_code: 'TANJUNG BIN',
        status: 'rejected',
        image: require('../assets/receipt.jpeg'),
        name: 'Ivan',
        department: 'Project Management Office',
        user_profile: require('../assets/henry_cavill.jpg'),
        invoice_date: 'Wed 01 01 2023 08:00:00 GMT+0800 (Malaysia Time)',
        submission_date: 'Wed 01 01 2023 08:00:00 GMT+0800 (Malaysia Time)'
    },
    {
        claim_id: '8',
        claim_type: 'Welfare',
        amount: 57.60,
        project_code: 'SARAWAK ENERGY ICT01/20',
        status: 'rejected',
        image: require('../assets/receipt.jpeg'),
        name: 'Elaine',
        department: 'HR & Admin',
        user_profile: require('../assets/henry_cavill.jpg'),
        invoice_date: 'Thu 01 02 2023 08:00:00 GMT+0800 (Malaysia Time)',
        submission_date: 'Thu 01 02 2023 08:00:00 GMT+0800 (Malaysia Time)'
    },
    {
        claim_id: '9',
        claim_type: 'Medical',
        amount: 274.10,
        project_code: 'OTHERS (ASPEN SPECTRA SDN BHD)',
        status: 'rejected',
        image: require('../assets/receipt.jpeg'),
        name: 'Elaine',
        department: 'HR & Admin',
        user_profile: require('../assets/henry_cavill.jpg'),
        invoice_date: 'Fri 01 03 2023 08:00:00 GMT+0800 (Malaysia Time)',
        submission_date: 'Fri 01 03 2023 08:00:00 GMT+0800 (Malaysia Time)'
    },
    {
        claim_id: '10',
        claim_type: 'Swab',
        amount: 56.90,
        project_code: 'DIGITAL FREE TRADE ZONE (DFTZ), KLIA (MAS/PCD/C/27/2020)',
        status: 'rejected',
        image: require('../assets/receipt.jpeg'),
        name: 'Martin',
        department: 'Channel & Enterprise Sales',
        user_profile: require('../assets/henry_cavill.jpg'),
        invoice_date: 'Thu 01 01 2023 08:00:00 GMT+0800 (Malaysia Time)',
        submission_date: 'Thu 01 01 2023 08:00:00 GMT+0800 (Malaysia Time)'
    },
    {
        claim_id: '11',
        claim_type: 'Entertainment',
        amount: 185.70,
        project_code: 'TM NEXT GENERATION VOICE PLATFORM 1.0',
        status: 'rejected',
        image: require('../assets/receipt.jpeg'),
        name: 'Ivan',
        department: 'Project Management Office',
        user_profile: require('../assets/henry_cavill.jpg'),
        invoice_date: 'Fri 01 02 2023 08:00:00 GMT+0800 (Malaysia Time)',
        submission_date: 'Fri 01 02 2023 08:00:00 GMT+0800 (Malaysia Time)'
    },
    {
        claim_id: '12',
        claim_type: 'Miscellaneous',
        amount: 628.10,
        project_code: 'TNB DCT SHAH ALAM_PO20908559',
        status: 'rejected',
        image: require('../assets/receipt.jpeg'),
        name: 'Ven Jin',
        department: 'Research & Development',
        user_profile: require('../assets/henry_cavill.jpg'),
        invoice_date: 'Sat 01 03 2023 08:00:00 GMT+0800 (Malaysia Time)',
        submission_date: 'Sat 01 03 2023 08:00:00 GMT+0800 (Malaysia Time)'
    },
    {
        claim_id: '13',
        claim_type: 'Lodging',
        amount: 85.50,
        project_code: 'TNB PMU GIS 436/2020',
        status: 'rejected',
        image: require('../assets/receipt.jpeg'),
        name: 'Ivan',
        department: 'Project Management Office',
        user_profile: require('../assets/henry_cavill.jpg'),
        invoice_date: 'Sun 12 04 2022 08:00:00 GMT+0800 (Malaysia Time)',
        submission_date: 'Sun 12 04 2022 08:00:00 GMT+0800 (Malaysia Time)'
    },
    {
        claim_id: '14',
        claim_type: 'Meal Subsidy',
        amount: 17.50,
        project_code: 'TNB PMU GIS 16 SITE',
        status: 'pending',
        image: require('../assets/receipt.jpeg'),
        name: 'Martin',
        department: 'Channel & Enterprise Sales',
        user_profile: require('../assets/henry_cavill.jpg'),
        invoice_date: 'Sun 12 04 2022 08:00:00 GMT+0800 (Malaysia Time)',
        submission_date: 'Sun 12 04 2022 08:00:00 GMT+0800 (Malaysia Time)'
    },
    {
        claim_id: '15',
        claim_type: 'Mileage',
        amount: 12.20,
        project_code: 'FELCRA PERAK',
        status: 'pending',
        image: require('../assets/receipt.jpeg'),
        name: 'Martin',
        department: 'Channel & Enterprise Sales',
        user_profile: require('../assets/henry_cavill.jpg'),
        invoice_date: 'Sun 12 04 2022 08:00:00 GMT+0800 (Malaysia Time)',
        submission_date: 'Sun 12 04 2022 08:00:00 GMT+0800 (Malaysia Time)'
    },
    {
        claim_id: '16',
        claim_type: 'Parking',
        amount: 65.50,
        project_code: 'FARMING CONTAINER',
        status: 'pending',
        image: require('../assets/receipt.jpeg'),
        name: 'Ivan',
        department: 'Project Management Office',
        user_profile: require('../assets/henry_cavill.jpg'),
        invoice_date: 'Sun 12 04 2022 08:00:00 GMT+0800 (Malaysia Time)',
        submission_date: 'Sun 12 04 2022 08:00:00 GMT+0800 (Malaysia Time)'
    },
    {
        claim_id: '17',
        claim_type: 'Petrol',
        amount: 200.90,
        project_code: 'CANON E-CLAIM',
        status: 'pending',
        image: require('../assets/receipt.jpeg'),
        name: 'Ven Jin',
        department: 'Research & Development',
        user_profile: require('../assets/henry_cavill.jpg'),
        invoice_date: 'Thu 12 02 2022 08:00:00 GMT+0800 (Malaysia Time)',
        submission_date: 'Thu 12 02 2022 08:00:00 GMT+0800 (Malaysia Time)'
    },
    {
        claim_id: '18',
        claim_type: 'Public Transport Fares',
        amount: 58.90,
        project_code: 'AQUA CULTURE AT PAHANG',
        status: 'pending',
        image: require('../assets/receipt.jpeg'),
        name: 'Ivan',
        department: 'Project Management Office',
        user_profile: require('../assets/henry_cavill.jpg'),
        invoice_date: 'Thu 12 02 2022 08:00:00 GMT+0800 (Malaysia Time)',
        submission_date: 'Thu 12 02 2022 08:00:00 GMT+0800 (Malaysia Time)'
    },
    {
        claim_id: '19',
        claim_type: 'Travel Requisition',
        amount: 835.40,
        project_code: 'CHERAS WAREHOUSE D-G-5',
        status: 'pending',
        image: require('../assets/receipt.jpeg'),
        name: 'Elaine',
        department: 'HR & Admin',
        user_profile: require('../assets/henry_cavill.jpg'),
        invoice_date: 'Thu 12 02 2022 08:00:00 GMT+0800 (Malaysia Time)',
        submission_date: 'Thu 12 02 2022 08:00:00 GMT+0800 (Malaysia Time)'
    },
    {
        claim_id: '20',
        claim_type: 'Welfare',
        amount: 59.90,
        project_code: 'ALLO - HUAWEI',
        status: 'pending',
        image: require('../assets/receipt.jpeg'),
        name: 'Ivan',
        department: 'Project Management Office',
        user_profile: require('../assets/henry_cavill.jpg'),
        invoice_date: 'Thu 12 02 2022 08:00:00 GMT+0800 (Malaysia Time)',
        submission_date: 'Thu 12 02 2022 08:00:00 GMT+0800 (Malaysia Time)'
    },
    {
        claim_id: '21',
        claim_type: 'Medical',
        amount: 683.60,
        project_code: 'METRO FARM AT SINGAPORE',
        status: 'pending',
        image: require('../assets/receipt.jpeg'),
        name: 'Ven Jin',
        department: 'Research & Development',
        user_profile: require('../assets/henry_cavill.jpg'),
        invoice_date: 'Thu 12 02 2022 08:00:00 GMT+0800 (Malaysia Time)',
        submission_date: 'Thu 12 02 2022 08:00:00 GMT+0800 (Malaysia Time)'
    },
    {
        claim_id: '22',
        claim_type: 'Swab',
        amount: 102.10,
        project_code: 'TNB 29 SITE- 5 PMU SELATAN',
        status: 'pending',
        image: require('../assets/receipt.jpeg'),
        name: 'Martin',
        department: 'Channel & Enterprise Sales',
        user_profile: require('../assets/henry_cavill.jpg'),
        invoice_date: 'Thu 12 02 2022 08:00:00 GMT+0800 (Malaysia Time)',
        submission_date: 'Thu 12 02 2022 08:00:00 GMT+0800 (Malaysia Time)'
    },
    {
        claim_id: '23',
        claim_type: 'Entertainment',
        amount: 294.40,
        project_code: 'TNB 29 SITE- 12 PMU CENTRAL',
        status: 'pending',
        image: require('../assets/receipt.jpeg'),
        name: 'Elaine',
        department: 'HR & Admin',
        user_profile: require('../assets/henry_cavill.jpg'),
        invoice_date: 'Thu 12 02 2022 08:00:00 GMT+0800 (Malaysia Time)',
        submission_date: 'Thu 12 02 2022 08:00:00 GMT+0800 (Malaysia Time)'
    },
    {
        claim_id: '24',
        claim_type: 'Miscellaneous',
        amount: 394.60,
        project_code: 'TNB STOR 1004/2022',
        status: 'pending',
        image: require('../assets/receipt.jpeg'),
        name: 'Ven Jin',
        department: 'Research & Development',
        user_profile: require('../assets/henry_cavill.jpg'),
        invoice_date: 'Sun 12 04 2022 08:00:00 GMT+0800 (Malaysia Time)',
        submission_date: 'Sun 12 04 2022 08:00:00 GMT+0800 (Malaysia Time)'
    },
    {
        claim_id: '25',
        claim_type: 'Toll',
        amount: 394.60,
        project_code: 'DCT UTARA',
        status: 'pending',
        image: require('../assets/receipt.jpeg'),
        name: 'Ven Jin',
        department: 'Research & Development',
        user_profile: require('../assets/henry_cavill.jpg'),
        invoice_date: 'Sun 12 04 2022 08:00:00 GMT+0800 (Malaysia Time)',
        submission_date: 'Sun 12 04 2022 08:00:00 GMT+0800 (Malaysia Time)'
    },
    {
        claim_id: '26',
        claim_type: 'Lodging',
        amount: 146.50,
        project_code: 'DCT SELATAN',
        status: 'pending',
        image: require('../assets/receipt.jpeg'),
        name: 'Elaine',
        department: 'HR & Admin',
        user_profile: require('../assets/henry_cavill.jpg'),
        invoice_date: 'Sun 02 04 2023 08:00:00 GMT+0800 (Malaysia Time)',
        submission_date: 'Sun 02 04 2023 08:00:00 GMT+0800 (Malaysia Time)'
    },
    {
        claim_id: '27',
        claim_type: 'Meal Subsidy',
        amount: 85.50,
        project_code: 'TNB ULU JELAI 103/2020',
        status: 'pending',
        image: require('../assets/receipt.jpeg'),
        name: 'Ivan',
        department: 'Project Management Office',
        user_profile: require('../assets/henry_cavill.jpg'),
        invoice_date: 'Sun 02 04 2023 08:00:00 GMT+0800 (Malaysia Time)',
        submission_date: 'Sun 02 04 2023 08:00:00 GMT+0800 (Malaysia Time)'
    },
    {
        claim_id: '28',
        claim_type: 'Mileage',
        amount: 54.20,
        project_code: 'SUNWAY ENGINEERING TNB HQ PHASE 2',
        status: 'pending',
        image: require('../assets/receipt.jpeg'),
        name: 'Ven Jin',
        department: 'Research & Development',
        user_profile: require('../assets/henry_cavill.jpg'),
        invoice_date: 'Sun 02 04 2023 08:00:00 GMT+0800 (Malaysia Time)',
        submission_date: 'Sun 02 04 2023 08:00:00 GMT+0800 (Malaysia Time)'
    },
    {
        claim_id: '29',
        claim_type: 'Parking',
        amount: 86.50,
        project_code: 'U-THANT RESIDENCE',
        status: 'pending',
        image: require('../assets/receipt.jpeg'),
        name: 'Elaine',
        department: 'HR & Admin',
        user_profile: require('../assets/henry_cavill.jpg'),
        invoice_date: 'Sun 02 04 2023 08:00:00 GMT+0800 (Malaysia Time)',
        submission_date: 'Sun 02 04 2023 08:00:00 GMT+0800 (Malaysia Time)'
    },
    {
        claim_id: '30',
        claim_type: 'Petrol',
        amount: 250.90,
        project_code: 'LIFESTYLE VPNNETWORK',
        status: 'approved',
        image: require('../assets/receipt.jpeg'),
        name: 'Ven Jin',
        department: 'Research & Development',
        user_profile: require('../assets/henry_cavill.jpg'),
        invoice_date: 'Thu 02 02 2023 08:00:00 GMT+0800 (Malaysia Time)',
        submission_date: 'Thu 02 02 2023 08:00:00 GMT+0800 (Malaysia Time)'
    },
    {
        claim_id: '31',
        claim_type: 'Public Transport Fares',
        amount: 97.90,
        project_code: 'MASB CAR PARKING BINTULU, SARAWAK',
        status: 'pending',
        image: require('../assets/receipt.jpeg'),
        name: 'Ivan',
        department: 'Project Management Office',
        user_profile: require('../assets/henry_cavill.jpg'),
        invoice_date: 'Thu 02 02 2023 08:00:00 GMT+0800 (Malaysia Time)',
        submission_date: 'Thu 02 02 2023 08:00:00 GMT+0800 (Malaysia Time)'
    },
    {
        claim_id: '32',
        claim_type: 'Travel Requisition',
        amount: 143.40,
        project_code: 'GRACE THAM YEE HOONG',
        status: 'pending',
        image: require('../assets/receipt.jpeg'),
        name: 'Elaine',
        department: 'HR & Admin',
        user_profile: require('../assets/henry_cavill.jpg'),
        invoice_date: 'Thu 02 02 2023 08:00:00 GMT+0800 (Malaysia Time)',
        submission_date: 'Thu 02 02 2023 08:00:00 GMT+0800 (Malaysia Time)'
    },
    {
        claim_id: '33',
        claim_type: 'Welfare',
        amount: 68.90,
        project_code: 'UPGRADE CARPARK IGB TGM MVM LOA#IGBR/LOA/SL/0026/18',
        status: 'approved',
        image: require('../assets/receipt.jpeg'),
        name: 'Ivan',
        department: 'Project Management Office',
        user_profile: require('../assets/henry_cavill.jpg'),
        invoice_date: 'Thu 02 02 2023 08:00:00 GMT+0800 (Malaysia Time)',
        submission_date: 'Thu 02 02 2023 08:00:00 GMT+0800 (Malaysia Time)'
    },
    {
        claim_id: '34',
        claim_type: 'Medical',
        amount: 64.60,
        project_code: 'MV CITY JMB LOA#006/mvcjmb/CCTV/LAEL/08-22',
        status: 'pending',
        image: require('../assets/receipt.jpeg'),
        name: 'Ven Jin',
        department: 'Research & Development',
        user_profile: require('../assets/henry_cavill.jpg'),
        invoice_date: 'Thu 02 02 2023 08:00:00 GMT+0800 (Malaysia Time)',
        submission_date: 'Thu 02 02 2023 08:00:00 GMT+0800 (Malaysia Time)'
    },
    {
        claim_id: '35',
        claim_type: 'Swab',
        amount: 102.10,
        project_code: 'KLIA UNIT 20',
        status: 'pending',
        image: require('../assets/receipt.jpeg'),
        name: 'Ven Jin',
        department: 'Research & Development',
        user_profile: require('../assets/henry_cavill.jpg'),
        invoice_date: 'Thu 02 02 2023 08:00:00 GMT+0800 (Malaysia Time)',
        submission_date: 'Thu 02 02 2023 08:00:00 GMT+0800 (Malaysia Time)'
    },
    {
        claim_id: '36',
        claim_type: 'Entertainment',
        amount: 294.40,
        project_code: 'KLIA UNIT 22',
        status: 'pending',
        image: require('../assets/receipt.jpeg'),
        name: 'Elaine',
        department: 'HR & Admin',
        user_profile: require('../assets/henry_cavill.jpg'),
        invoice_date: 'Thu 02 02 2023 08:00:00 GMT+0800 (Malaysia Time)',
        submission_date: 'Thu 02 02 2023 08:00:00 GMT+0800 (Malaysia Time)'
    },
    {
        claim_id: '37',
        claim_type: 'Miscellaneous',
        amount: 344.60,
        project_code: 'SEPUTEH HOSTEL',
        status: 'pending',
        image: require('../assets/receipt.jpeg'),
        name: 'Ivan',
        department: 'Project Management Office',
        user_profile: require('../assets/henry_cavill.jpg'),
        invoice_date: 'Sun 02 04 2023 08:00:00 GMT+0800 (Malaysia Time)',
        submission_date: 'Sun 02 04 2023 08:00:00 GMT+0800 (Malaysia Time)'
    },
    {
        claim_id: '38',
        claim_type: 'Toll',
        amount: 94.60,
        project_code: 'NG GIM GUAN',
        status: 'pending',
        image: require('../assets/receipt.jpeg'),
        name: 'Elaine',
        department: 'HR & Admin',
        user_profile: require('../assets/henry_cavill.jpg'),
        invoice_date: 'Sun 02 04 2023 08:00:00 GMT+0800 (Malaysia Time)',
        submission_date: 'Sun 02 04 2023 08:00:00 GMT+0800 (Malaysia Time)'
    },
    {
        claim_id: '39',
        claim_type: 'Toll',
        amount: 244.60,
        project_code: 'TM BACKUP SOLUTION',
        status: 'pending',
        image: require('../assets/receipt.jpeg'),
        name: 'Ven Jin',
        department: 'Research & Development',
        user_profile: require('../assets/henry_cavill.jpg'),
        invoice_date: 'Sun 01 04 2023 08:00:00 GMT+0800 (Malaysia Time)',
        submission_date: 'Sun 01 04 2023 08:00:00 GMT+0800 (Malaysia Time)'
    }
];

const sampleUsers =[
    {
        user_id: 1,
        name: 'Ven Jin',
        department: 'Research & Development',
        user_profile: require('../assets/henry_cavill.jpg')
    },
    {
        user_id: 2,
        name: 'Ivan',
        department: 'Project Management Office',
        user_profile: require('../assets/henry_cavill.jpg')
    },
    {
        user_id: 3,
        name: 'Elaine',
        department: 'HR & Admin',
        user_profile: require('../assets/henry_cavill.jpg')
    },
    {
        user_id: 3,
        name: 'Martin',
        department: 'Channel & Enterprise Sales',
        user_profile: require('../assets/henry_cavill.jpg')
    }
]

export{
    sampleClaims,
    sampleUsers
}